upgrading_to_fusion:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: your_account_id

      user: trouze
      password: your_password_here # enter password you used to signup for Snowflake demo account here
      role: ACCOUNTADMIN
      
      database: analytics
      warehouse: compute_wh
      schema: dbt_trouze